#!/bin/zsh

# name of job
#$ -N whizard-ttH-scan

# Note on queues:
# default.q     100 % (h_rt < 3:00:00, h_vmem < 2G/8G)
# short.q appr. 85 %  (h_rt < 24:00:00, h_vmem < 2G/16G)
# long.q        50 %  (24:00:00 < h_rt < 168:00:00, h_vmem < 4G/32G)
# On our big birds memory limits are extended to h_vmem=8G+

# Max run time
##$ -l h_rt=00:04:59
##$ -l h_rt=02:59:59
#$ -l h_rt=23:59:59
##$ -l h_rt=47:59:59

# Max available memory (default 1G)
##$ -l h_vmem=1900M
##$ -l h_vmem=15900M
#$ -l h_vmem=6900M

# Max available disk space (default 3G)
#$ -l h_fsize=3000M

# Request Scientific Linux 6
#$ -l os=sld6

# Request 64 bit
#$ -l arch=amd64

# request Bourne shell as shell for job
#$ -S /bin/zsh

# Send mail after the end(e), begin(b), abort(a) or suspend(s) of the batch jobs
##$ -m as

# Mail for notifications
##$ -M bijan.chokoufe@desy.de

# Use current working directory
#$ -cwd

# Join stdout and stderr
#$ -j y

if ! test -z $FOLDER ; then
  cd $FOLDER
fi
echo "Got $NSLOTS processors."
echo "This is job: $JOB_ID and runs in `pwd`"

#make
source $HOME/.commonrc
whizard *.sin

#rm fifo.hepmc
#mkfifo fifo.hepmc
#source $HOME/.bashrc
#whizard -r *.sin &
#rivet -a DELPHI_1996_S3430090 fifo.hepmc
